# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e559838bc479713b8c6f0cebdf2f79e3afe38475bd80aa028d8301fadd9b5251f5494b4911579e2a984559aa3209592264e41c87b19c6cbdeec870ae6ec44a5
  riot_api_key: "RGAPI-09e7a87f-60a6-48ba-af2f-9955468cc26d"

test:
  secret_key_base: 87a2985b53d27740fdfdbe043f4dea56336fca3c7849b6dd59c8a310726833032d3a8a56cf3edff45d4148fabc4ff14006ab461a45b5d4ca796e0a90f1f05be4
  riot_api_key: "RGAPI-09e7a87f-60a6-48ba-af2f-9955468cc26d"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  riot_api_key: <%= ENV["RIOT_API_KEY"] %>
